### ISSUE TITLE
Crash error

### ISSUE THREAD

**Issue by Zelurium** [WolfDen133/WFT#15]
2:28:29.697] [Server thread/CRITICAL]: InvalidArgumentException: "Cannot use non-existing permission "formcreator.simpleeg.use"" (EXCEPTION) in "pmsrc/src/command/Command" at line 107

**Comment by ErosionYT** [comment]
that permission isnt in this plugin

**Comment by WolfDen133** [comment]
That seems to be for my other plugin [FormCreator](https://github.com/WolfDen133/FormCreator)
