### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by GamerMJay** [WolfDen133/WFT#16]
[17:35:30.861] [Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\protocol\AddPlayerPacket::create(): Argument #12 ($gameMode) must be of type int, array given, called in phar:///home/minecraft/plugins/WFT.phar/src/WolfDen133/WFT/Texts/SubText.php on line 105" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AddPlayerPacket" at line 60

**Comment by PSYCHO678** [comment]
same here

**Comment by WolfDen133** [comment]
Please use the issue template to provide some more information about this bug, as just with this error I cannot diagnose what is wrong, can I ask how/when this error occored?

**Comment by GamerMJay** [comment]
I updated my server to 1.18.30 am joined then came server closed is due to the plugin

**Comment by Tuvqlu** [comment]
Same thing here as well

**Comment by HomeTreeBE** [comment]
I fixed it,

Just replace this part in text/subtext

$pks[] = AddPlayerPacket::create(
            UUID::fromString($this->uuid),
            $this->text,
            $this->runtime,
            $this->runtime,
            "",
            $this->position->asVector3(),
            null,
            0,
            0,
            0,		
            ItemStackWrapper::legacy(ItemStack::null()),
			1,
            [
                EntityMetadataProperties::FLAGS => new LongMetadataProperty(1 << EntityMetadataFlags::IMMOBILE),
                EntityMetadataProperties::SCALE => new FloatMetadataProperty(0)
            ],
            AdventureSettingsPacket::create(0, 0, 0, 0, 0, $this->runtime),
            [],
            "",
            DeviceOS::UNKNOWN
        );

**Comment by WolfDen133** [comment]
Updated and fixed, pushing now
