### ISSUE TITLE
error (1.19.10)

### ISSUE THREAD

**Issue by GamerMJay** [WolfDen133/WFT#19]
2022-07-13 [15:21:45.332] [Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\protocol\AddPlayerPacket::create(): Argument #5 ($position) must be of type pocketmine\math\Vector3, string given, called in phar:///home/minecraft/plugins/WFT_dev-80.phar/src/WolfDen133/WFT/Texts/SubText.php on line 99" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/AddPlayerPacket" at line 59
--- Stack trace ---
  #0 plugins/WFT_dev-80.phar/src/WolfDen133/WFT/Texts/SubText(99): pocketmine\network\mcpe\protocol\AddPlayerPacket::create(object Ramsey\Uuid\Lazy\LazyUuidFromString#300754, string[12] ..6..lInfos , int 5, string[1] 5, string[0] , object pocketmine\math\Vector3#300755, null, int 0, int 0, int 0, object pocketmine\network\mcpe\protocol\types\inventory\ItemStackWrapper#300757, int 1, array[2], object pocketmine\network\mcpe\protocol\AdventureSettingsPacket#300763, array[0], string[0] , int -1)
  #1 plugins/WFT_dev-80.phar/src/WolfDen133/WFT/Texts/FloatingText(103): WolfDen133\WFT\Texts\SubText->spawnTo(object ipad54\netherblocks\player\Player#302007)
  #2 plugins/WFT_dev-80.phar/src/WolfDen133/WFT/API(98): WolfDen133\WFT\Texts\FloatingText->spawnTo(object ipad54\netherblocks\player\Player#302007)
  #3 plugins/WFT_dev-80.phar/src/WolfDen133/WFT/API(63): WolfDen133\WFT\API::spawnTo(object ipad54\netherblocks\player\Player#302007, object WolfDen133\WFT\Texts\FloatingText#290175)
  #4 plugins/WFT_dev-80.phar/src/WolfDen133/WFT/EventListener(20): WolfDen133\WFT\API->spawn

**Comment by WolfDen133** [comment]
Fixed
