### ISSUE TITLE
error in 1.19.40 (pmmp 4.10.0)

### ISSUE THREAD

**Issue by jaylac2000** [WolfDen133/WFT#20]
**Describe the bug**

server crash on server join

it was narrowed down to this plugin

**Error**
Full error with stacktrace
e.g.
```
Syntax error: "Unexpected '$var' on line 12 in file PocketMine\Plugin\Main.php"
## Stack trace

check link in additional 

```

**To Reproduce**
e.g.
1. join server

**Expected behavior**

not to crash my server when someone joins

**Screenshots**

**Desktop (please complete the following information):**
 - latest poggit release
 - look in title

**Additional context**
https://crash.pmmp.io/view/7719577

**Comment by WolfDen133** [comment]
Fixed

**Comment by jaylac2000** [comment]
thanks!

**Comment by WolfDen133** [comment]
Always happy to help

**Comment by WolfDen133** [comment]
Im happy with the plugin where it is at the moment, so no new features are planned unless they are suggested and i like them, but the plugin will be updated until further notice!
