### ISSUE TITLE
Crash on load

### ISSUE THREAD

**Issue by EmporiumDevelopment** [WolfDen133/WFT#21]
**Describe the bug**

**Error**
[Server thread/CRITICAL]: TypeError: "pocketmine\network\mcpe\protocol\UpdateAbilitiesPacket::create(): Argument #1 ($data) must be of type pocketmine\network\mcpe\protocol\types\AbilitiesData, int given, called in phar://C:/Users/brant/Desktop/EmporiumPrison/plugins/WFT.phar/src/WolfDen133/WFT/Texts/SubText.php on line 93" (EXCEPTION) in "pmsrc/vendor/pocketmine/bedrock-protocol/src/UpdateAbilitiesPacket" at line 32
--- Stack trace ---
  #0 plugins/WFT.phar/src/WolfDen133/WFT/Texts/SubText(93): pocketmine\network\mcpe\protocol\UpdateAbilitiesPacket::create(int 0, int 0, int 5, array[0])
  #1 plugins/WFT.phar/src/WolfDen133/WFT/Texts/FloatingText(103): WolfDen133\WFT\Texts\SubText->spawnTo(object pocketmine\player\Player#126021)
  #2 plugins/WFT.phar/src/WolfDen133/WFT/API(73): WolfDen133\WFT\Texts\FloatingText->spawnTo(object pocketmine\player\Player#126021)
  #3 plugins/WFT.phar/src/WolfDen133/WFT/API(24): WolfDen133\WFT\API::spawnToAll(object WolfDen133\WFT\Texts\FloatingText#155493)
  #4 plugins/EmporiumPrison/src/Emporium/Prison/listeners/player/PlayerListener(104): WolfDen133\WFT\API->registerText(object WolfDen133\WFT\Texts\FloatingText#155493)
  #5 pmsrc/src/event/RegisteredListener(60): Emporium\Prison\listeners\player\PlayerListener->onJoin(object pocketmine\event\player\PlayerJoinEvent#155426)
  #6 pmsrc/src/event/Event(62): pocketmine\event\RegisteredListener->callEvent(object pocketmine\event\player\PlayerJoinEvent#155426)
  #7 pmsrc/src/player/Player(871): pocketmine\event\Event->call()
  #8 pmsrc/src/network/mcpe/NetworkSession(774): pocketmine\player\Player->doFirstSpawn()
  #9 pmsrc/src/network/mcpe/NetworkSession(767): pocketmine\network\mcpe\NetworkSession->onClientSpawnResponse()
  #10 pmsrc/src/network/mcpe/handler/SpawnResponsePacketHandler(37): pocketmine\network\mcpe\NetworkSession->pocketmine\network\mcpe\{closure}()
  #11 pmsrc/vendor/pocketmine/bedrock-protocol/src/SetLocalPlayerAsInitializedPacket(42): pocketmine\network\mcpe\handler\SpawnResponsePacketHandler->handleSetLocalPlayerAsInitialized(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#155488)
  #12 pmsrc/src/network/mcpe/NetworkSession(451): pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket->handle(object pocketmine\network\mcpe\handler\SpawnResponsePacketHandler#150455)
  #13 pmsrc/src/network/mcpe/NetworkSession(407): pocketmine\network\mcpe\NetworkSession->handleDataPacket(object pocketmine\network\mcpe\protocol\SetLocalPlayerAsInitializedPacket#155488, string[2] q.)
  #14 pmsrc/src/network/mcpe/raklib/RakLibInterface(189): pocketmine\network\mcpe\NetworkSession->handleEncoded(string[58] c*d.Wda\{_.....S..........f.....&`...K.0@.H....A.....`/...)
  #15 pmsrc/vendor/pocketmine/raklib-ipc/src/RakLibToUserThreadMessageReceiver(42): pocketmine\network\mcpe\raklib\RakLibInterface->onPacketReceive(int 0, string[67] .....)..{.6..W.>Z.[.v.&t....J.]G.n........X..!.D....L..........,`..)
  #16 pmsrc/src/network/mcpe/raklib/RakLibInterface(116): raklib\server\ipc\RakLibToUserThreadMessageReceiver->handle(object pocketmine\network\mcpe\raklib\RakLibInterface#26425)
  #17 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(123): pocketmine\network\mcpe\raklib\RakLibInterface->pocketmine\network\mcpe\raklib\{closure}()
  #18 pmsrc/src/TimeTrackingSleeperHandler(58): pocketmine\snooze\SleeperHandler->processNotifications()
  #19 pmsrc/vendor/pocketmine/snooze/src/SleeperHandler(82): pocketmine\TimeTrackingSleeperHandler->processNotifications()
  #20 pmsrc/src/Server(1695): pocketmine\snooze\SleeperHandler->sleepUntil(float 1675945479.4488)
  #21 pmsrc/src/Server(1053): pocketmine\Server->tickProcessor()
  #22 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#5, object pocketmine\utils\MainLogger#2, string[38] C:\Users\brant\Desktop\EmporiumPrison\, string[46] C:\Users\brant\Desktop\EmporiumPrison\plugins\)
  #23 pmsrc/src/PocketMine(362): pocketmine\server()
  #24 pmsrc(11): require(string[82] phar://C:/Users/brant/Desktop/EmporiumPrison/PocketMine-MP.phar/src/PocketMine.p)
--- End of exception information ---
[12:24:39.414] [Server thread/EMERGENCY]: An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[12:24:39.421] [Server thread/EMERGENCY]: Please upload the "C:/Users/brant/Desktop/EmporiumPrison/crashdumps/Thu_Feb_9-12.24.39-UTC_2023.log" file to the Crash Archive and submit the link to the Bug Reporting page. Give as much info as you can.
[12:24:39.645] [Server thread/EMERGENCY]: The crash dump has been automatically submitted to the Crash Archive. You can view it on https://crash.pmmp.io/view/8285905 or use the ID #8285905.
[12:24:39.650] [Server thread/EMERGENCY]: Forcing server shutdown
```

**Desktop (please complete the following information):**
 - WFT Version 1.3.5
 - Pocketmine Version 4.14.0

**Comment by WolfDen133** [comment]
Fixed
