### ISSUE TITLE
console Error

### ISSUE THREAD

**Issue by slayerzim** [WolfDen133/WFT#22]
Error: Cannot use non-existing permission "formcreator.simpleeg.use"
File: pmsrc/src/command/Command
Line: 99
Type: InvalidArgumentException
Backtrace:
#0 plugins/FormCreator-main.phar/src/WolfDen133/FormCreator/OpenFormCommand(36): pocketmine\command\Command->setPermission(string[24] formcreator.simpleeg.use)
#1 plugins/FormCreator-main.phar/src/WolfDen133/FormCreator/FormCreator(255): WolfDen133\FormCreator\OpenFormCommand->__construct(object WolfDen133\FormCreator\FormCreator#29483, string[7] example, string[14] opensimpleform, string[24] formcreator.simpleeg.use, string[20] Opens the example ui)
#2 plugins/FormCreator-main.phar/src/WolfDen133/FormCreator/FormCreator(188): WolfDen133\FormCreator\FormCreator->loadSimpleForm(string[7] example, array[5])
#3 plugins/FormCreator-main.phar/src/WolfDen133/FormCreator/FormCreator(85): WolfDen133\FormCreator\FormCreator->loadForms()
#4 pmsrc/src/plugin/PluginBase(118): WolfDen133\FormCreator\FormCreator->onEnable()
#5 pmsrc/src/plugin/PluginManager(454): pocketmine\plugin\PluginBase->onEnableStateChange(true)
#6 pmsrc/src/Server(1409): pocketmine\plugin\PluginManager->enablePlugin(object WolfDen133\FormCreator\FormCreator#29483)
#7 pmsrc/src/Server(1022): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21910)
#8 pmsrc/src/PocketMine(339): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#5, string[16] /home/container/, string[24] /home/container/plugins/)
#9 pmsrc/src/PocketMine(362): pocketmine\server()
#10 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php

**Comment by WolfDen133** [comment]
Hiya, your at the wrong page, this issue relates to my other plugin [FormCreator](https://github.com/WolfDen133/FormCreator)
