### ISSUE TITLE
Respawning the text

### ISSUE THREAD

**Issue by EmporiumDevelopment** [WolfDen133/WFT#23]
How can i respawn the text?

Im creating and registering the texts in a plugin, and i have it set the update every 5 minutes but the texts just stack they dont respawn, and it eventually gets too dark to read, and lags

**Comment by WolfDen133** [comment]
Hiya, would you like to tell me your discord so we can discuss the issue further as I'm aware that WFT has a bit of a difficult API

**Comment by EmporiumDevelopment** [comment]
Tetro#0448

**Comment by WolfDen133** [comment]
Fixed in the latest update
